### PR TITLE
Renamed `yanked` to `retired`

### PR DESCRIPTION
**Pull request by idyll**
This PR renames `yanked` to `retired` to better represent that the package is not actually pulled.

Note that I changed the `YankStatus` to be `RetirementStatus` because it felt more natural to me than RetireStatus or RetiredStatus. Let me know if you want that changed.

### CODE REVIEW

**Comment by ericmj** [comment]
Looks good.

Btw, did you recompile the protocol buffer files or did you do search-replace on the produced `.erl`files?

**Comment by idyll** [comment]
:( find and replace... I didn't realize you compiled those.

**Comment by ericmj** [comment]
Okay, can you remove the erl changes and I will recompile them?

**Comment by ericmj** [comment]
Ping? :)

**Comment by ericmj** [comment]
I am going to merge this manually.

**Pull request closed without merging**
